name: PitchBlack Recovery Project Builder

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'PBRP Manifest Branch'
        required: true
        default: 'android-12.1'
        type: choice
        options:
        - android-14.0
        - android-12.1
        - android-11.0
        - android-10.0
        - android-9.0
        - android-8.1
        - android-7.1
        - android-6.0
      DEVICE_TREE:
        description: 'Custom Recovery Tree URL'
        required: true
        default: 'https://github.com/Romeo13card-sys/android_device_xiaomi_xun-recovery'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch (optional)'
        required: false
        default: ''
      BUILD_TARGET:
        description: 'Build Target (use "pbrp" for Android 11+)'
        required: true
        default: 'pbrp'
        type: choice
        options:
        - pbrp
        - recovery
        - boot
        - vendorboot
      LDCHECK_PATH:
        description: 'Path for dependency check (optional)'
        required: false
        default: 'recovery/root/system/bin/qseecomd'

jobs:
  build:
    name: Build PBRP by ${{ github.actor }}
    runs-on: ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
      OUTPUT_DIR: ${{ github.workspace }}/out
      DEVICE_NAME: xun
    permissions:
      contents: write
      
    steps:
    - name: Initial Setup
      run: |
        echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
        echo "BUILD_DATE=$(TZ=UTC date +%Y%m%d)" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Check Device Tree Branch
      run: |
        BRANCH=${{ inputs.DEVICE_TREE_BRANCH }}
        if [ -z "$BRANCH" ]; then
          echo "DEVICE_TREE_BRANCH=main" >> $GITHUB_ENV
        else
          if git ls-remote --exit-code --heads ${{ inputs.DEVICE_TREE }} $BRANCH; then
            echo "DEVICE_TREE_BRANCH=$BRANCH" >> $GITHUB_ENV
          else
            echo "Branch $BRANCH not found, using main"
            echo "DEVICE_TREE_BRANCH=main" >> $GITHUB_ENV
          fi
        fi

    - name: Init Repo
      run: |
        repo init -u https://github.com/PitchBlack-Devices/manifest -b ${{ inputs.MANIFEST_BRANCH }}
        repo sync -c -j$(nproc)

    - name: Clone Device Tree
      run: |
        git clone --branch ${{ env.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE }} device/$DEVICE_NAME

    - name: Build PitchBlack Recovery
      uses: mlm-games/pitchblack-pbrp-builder-action@main
      id: build
      with:
        MANIFEST_BRANCH: ${{ inputs.MANIFEST_BRANCH }}
        DEVICE_TREE:  ${{ inputs.DEVICE_TREE }}
        DEVICE_TREE_BRANCH:  ${{ env.DEVICE_TREE_BRANCH }}
        BUILD_TARGET:  ${{ inputs.BUILD_TARGET }}

    - name: Calculate MD5
      run: |
        cd ${{ env.OUTPUT_DIR }}
        if ls *.img 1> /dev/null 2>&1; then
          MD5_IMG=$(md5sum *.img | cut -d ' ' -f1)
          echo "MD5_IMG=$MD5_IMG" >> $GITHUB_ENV
        fi
        if ls PBRP*.zip 1> /dev/null 2>&1; then
          MD5_ZIP=$(md5sum PBRP*.zip | cut -d ' ' -f1)
          echo "MD5_ZIP=$MD5_ZIP" >> $GITHUB_ENV
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PBRP-Recovery-${{ env.DEVICE_NAME }}-${{ env.BUILD_DATE }}
        path: |
          ${{ env.OUTPUT_DIR }}/*.img
          ${{ env.OUTPUT_DIR }}/*.tar
          ${{ env.OUTPUT_DIR }}/*vbmeta*
          ${{ env.OUTPUT_DIR }}/*.cpio

    - name: Upload to Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.OUTPUT_DIR }}/*.img
          ${{ env.OUTPUT_DIR }}/PBRP*.zip
        name: PBRP for ${{ env.DEVICE_NAME }} - ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## Build Information
          - **Build Date:** ${{ env.BUILD_DATE }}
          - **Branch:** ${{ inputs.MANIFEST_BRANCH }}
          - **Device:** ${{ env.DEVICE_NAME }}
          - **Build Type:** ${{ inputs.BUILD_TARGET }}
          
          ## Source Information
          - **Device Tree:** [${{ inputs.DEVICE_TREE }}](${{ inputs.DEVICE_TREE }}/tree/${{ env.DEVICE_TREE_BRANCH }})
          - **Branch:** ${{ env.DEVICE_TREE_BRANCH }}
          
          ## Build Status
          - Recovery Image MD5: `${{ env.MD5_IMG }}`
          - ZIP Package MD5: `${{ env.MD5_ZIP }}`
        prerelease: false
        draft: false

    - name: Run LDCHECK
      uses: mlm-games/ldcheck-action@main
      with:
        OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
        LDCHECKPATH: ${{ inputs.LDCHECK_PATH }}
      continue-on-error: true

    - name: Calculate Build Time
      if: always()
      run: |
        BUILD_END=$(date +%s)
        BUILD_DURATION=$((BUILD_END - BUILD_START))
        
        hours=$((BUILD_DURATION / 3600))
        minutes=$(((BUILD_DURATION % 3600) / 60))
        seconds=$((BUILD_DURATION % 60))
        
        echo "Build completed in ${hours}h ${minutes}m ${seconds}s"
        
        echo "BUILD_DURATION=${BUILD_DURATION}" >> $GITHUB_ENV
        echo "BUILD_HOURS=${hours}" >> $GITHUB_ENV
        echo "BUILD_MINUTES=${minutes}" >> $GITHUB_ENV
        echo "BUILD_SECONDS=${seconds}" >> $GITHUB_ENV

    - name: Cleanup Workspace
      if: always()
      run: |
        cd ${{ github.workspace }}
        rm -rf android-recovery
        df -h
